apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: noelo-poi-map-app-dev
  annotations:
    argocd/app-name: noelo-poi-map-app-dev
    backstage.io/kubernetes-id: noelo-poi-map-app-dev
    backstage.io/kubernetes-namespace: noelo
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=noelo-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    janus-idp.io/tekton-enabled : 'false'
    github.com/project-slug: Summit23Janus1/noelo-frontend
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/noelo/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/noelo/deployments/poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/noelo-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://poi-map-app-noelo.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/noelo"
  system: workshop-system-noelo
  consumesApis:
    - gateway-api-noelo
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-noelo
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/noelo"
